apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    name: client-pod
    app: React-app
spec:
  containers: 
    - name: client-app
      image: beellzrocks/multi-docker_client
      ports:
        - containerPort: 3000