apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
    app: React-app
spec:
  containers: 
    - name: nginx-app
      image: beellzrocks/multi-docker-nginx
      ports:
        - containerPort: 3050