apiVersion: v1
kind: Service
metadata: 
  name: api-app
  labels: 
    name: api-service
    app: React-app
spec:
  type: NodePort 
  ports: 
    - port: 5000
      targetPort: 5000
      nodePort: 30005
  selector:
    name: client-pod
    app: React-app