apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  labels: 
    name: nginx-service
    app: React-app
spec:
  type: NodePort 
  ports: 
    - port: 3050
      targetPort: 3050
      nodePort: 30000
  selector:
    name: nginx-pod
    app: React-app